package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FRIEND".
 */
public class Friend {

    private Long id;
    private String friendId;
    private String friendHash;
    private String userId;

    public Friend() {
    }

    public Friend(Long id) {
        this.id = id;
    }

    public Friend(Long id, String friendId, String friendHash, String userId) {
        this.id = id;
        this.friendId = friendId;
        this.friendHash = friendHash;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFriendId() {
        return friendId;
    }

    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    public String getFriendHash() {
        return friendHash;
    }

    public void setFriendHash(String friendHash) {
        this.friendHash = friendHash;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
