package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_NOTIFY".
 */
public class MessageNotify implements Cloneable{

    private String msgId;
    private String title;
    private String newTxId;
    private String content;
    private Integer type;
    private java.util.Date time;
    private String userId;
    private Boolean isRead;
    private String lotteryId;
    private String hornContent;

    public MessageNotify() {
    }

    public MessageNotify(String msgId) {
        this.msgId = msgId;
    }

    public MessageNotify(String msgId, String title, String newTxId, String content, Integer type, java.util.Date time, String userId, Boolean isRead, String lotteryId, String hornContent) {
        this.msgId = msgId;
        this.title = title;
        this.newTxId = newTxId;
        this.content = content;
        this.type = type;
        this.time = time;
        this.userId = userId;
        this.isRead = isRead;
        this.lotteryId = lotteryId;
        this.hornContent = hornContent;
    }

    public Object clone()
    {
        MessageNotify o = null;
        try
        {
            o = (MessageNotify) super.clone();
        }
        catch (CloneNotSupportedException e)
        {
        }
        return o;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNewTxId() {
        return newTxId;
    }

    public void setNewTxId(String newTxId) {
        this.newTxId = newTxId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public String getLotteryId() {
        return lotteryId;
    }

    public void setLotteryId(String lotteryId) {
        this.lotteryId = lotteryId;
    }

    public String getHornContent() {
        return hornContent;
    }

    public void setHornContent(String hornContent) {
        this.hornContent = hornContent;
    }

}
