package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.peersafe.chainbet.utils.common.ConstantCode;

/**
 * Entity mapped to table "ONE_LOTTERY".
 */
public class OneLottery implements Cloneable
{

    private String lotteryId;
    private String newTxId;
    private Integer version;
    private String lotteryName;
    private String ruleType;
    private String ruleId;
    private String publisherHash;
    private String publisherName;
    private java.util.Date createTime;
    private java.util.Date updateTime;
    private java.util.Date startTime;
    private java.util.Date closeTime;
    private Integer minBetCount;
    private java.util.Date rewardCountDownTime;
    private Integer maxBetCount;
    private Long oneBetCost;
    private String description;
    private java.util.Date lastCloseTime;
    private Long curBetAmount;
    private Long betTotalAmount;
    private Integer curBetCount;
    private String rewardNumbers;
    private Integer state;
    private String betTxnIDs;
    private Long curBlockHeight;
    private Long prevBlockHeight;
    private Long lastUpadteBlockHeight;
    private String updateFlag;
    private Integer pictureIndex;
    private Integer progress;
    private String prizeTxID;

    public Object clone()
    {
        OneLottery o = null;
        try
        {
            o = (OneLottery) super.clone();
        }
        catch (CloneNotSupportedException e)
        {
        }
        return o;
    }

    public OneLottery()
    {
    }

    public OneLottery(String lotteryId)
    {
        this.lotteryId = lotteryId;
    }

    public OneLottery(String lotteryId, String newTxId, Integer version, String lotteryName,
                      String ruleType, String ruleId, String publisherHash, String publisherName,
                      java.util.Date createTime, java.util.Date updateTime, java.util.Date
                              startTime, java.util.Date closeTime, Integer minBetCount, java.util
                              .Date rewardCountDownTime, Integer maxBetCount, Long oneBetCost,
                      String description, java.util.Date lastCloseTime, Long curBetAmount, Long
                              betTotalAmount, Integer curBetCount, String rewardNumbers, Integer
                              state, String betTxnIDs, Long curBlockHeight, Long prevBlockHeight,
                      Long lastUpadteBlockHeight, String updateFlag, Integer pictureIndex,
                      Integer progress, String prizeTxID)
    {
        this.lotteryId = lotteryId;
        this.newTxId = newTxId;
        this.version = version;
        this.lotteryName = lotteryName;
        this.ruleType = ruleType;
        this.ruleId = ruleId;
        this.publisherHash = publisherHash;
        this.publisherName = publisherName;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.startTime = startTime;
        this.closeTime = closeTime;
        this.minBetCount = minBetCount;
        this.rewardCountDownTime = rewardCountDownTime;
        this.maxBetCount = maxBetCount;
        this.oneBetCost = oneBetCost;
        this.description = description;
        this.lastCloseTime = lastCloseTime;
        this.curBetAmount = curBetAmount;
        this.betTotalAmount = betTotalAmount;
        this.curBetCount = curBetCount;
        this.rewardNumbers = rewardNumbers;
        this.state = state;
        this.betTxnIDs = betTxnIDs;
        this.curBlockHeight = curBlockHeight;
        this.prevBlockHeight = prevBlockHeight;
        this.lastUpadteBlockHeight = lastUpadteBlockHeight;
        this.updateFlag = updateFlag;
        this.pictureIndex = pictureIndex;
        this.progress = progress;
        this.prizeTxID = prizeTxID;
    }

    public String getLotteryId()
    {
        return lotteryId;
    }

    public void setLotteryId(String lotteryId)
    {
        this.lotteryId = lotteryId;
    }

    public String getNewTxId()
    {
        return newTxId;
    }

    public void setNewTxId(String newTxId)
    {
        this.newTxId = newTxId;
    }

    public Integer getVersion()
    {
        return version != null ? version : 0;
    }

    public void setVersion(Integer version)
    {
        this.version = version;
    }

    public String getLotteryName()
    {
        return lotteryName;
    }

    public void setLotteryName(String lotteryName)
    {
        this.lotteryName = lotteryName;
    }

    public String getRuleType()
    {
        return ruleType;
    }

    public void setRuleType(String ruleType)
    {
        this.ruleType = ruleType;
    }

    public String getRuleId()
    {
        return ruleId;
    }

    public void setRuleId(String ruleId)
    {
        this.ruleId = ruleId;
    }

    public String getPublisherHash()
    {
        return publisherHash;
    }

    public void setPublisherHash(String publisherHash)
    {
        this.publisherHash = publisherHash;
    }

    public String getPublisherName()
    {
        return publisherName;
    }

    /**
     * UI中显示创建者，房主等地方用时采用这个方法
     */
    public String getPublisherName2()
    {
        return ConstantCode.CommonConstant.ONELOTTERY_DEFAULT_OFFICAL_NAME.equals(publisherName) ? "官方" : publisherName;
    }

    public void setPublisherName(String publisherName)
    {
        this.publisherName = publisherName;
    }

    public java.util.Date getCreateTime()
    {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime)
    {
        this.createTime = createTime;
    }

    public java.util.Date getUpdateTime()
    {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime)
    {
        this.updateTime = updateTime;
    }

    public java.util.Date getStartTime()
    {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime)
    {
        this.startTime = startTime;
    }

    public java.util.Date getCloseTime()
    {
        return closeTime;
    }

    public void setCloseTime(java.util.Date closeTime)
    {
        this.closeTime = closeTime;
    }

    public Integer getMinBetCount()
    {
        return minBetCount != null ? minBetCount : 0;
    }

    public void setMinBetCount(Integer minBetCount)
    {
        this.minBetCount = minBetCount;
    }

    public java.util.Date getRewardCountDownTime()
    {
        return rewardCountDownTime;
    }

    public void setRewardCountDownTime(java.util.Date rewardCountDownTime)
    {
        this.rewardCountDownTime = rewardCountDownTime;
    }

    public Integer getMaxBetCount()
    {
        return maxBetCount != null ? maxBetCount.intValue() : 0;
    }

    public void setMaxBetCount(Integer maxBetCount)
    {
        this.maxBetCount = maxBetCount;
    }

    public Long getOneBetCost()
    {
        return oneBetCost != null ? oneBetCost : 0;
    }

    public void setOneBetCost(Long oneBetCost)
    {
        this.oneBetCost = oneBetCost;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public java.util.Date getLastCloseTime()
    {
        return lastCloseTime;
    }

    public void setLastCloseTime(java.util.Date lastCloseTime)
    {
        this.lastCloseTime = lastCloseTime;
    }

    public Long getCurBetAmount()
    {
        return curBetAmount != null ? curBetAmount : 0;
    }

    public void setCurBetAmount(Long curBetAmount)
    {
        this.curBetAmount = curBetAmount;
    }

    public Long getBetTotalAmount()
    {
        return betTotalAmount != null ? betTotalAmount : 0;
    }

    public void setBetTotalAmount(Long betTotalAmount)
    {
        this.betTotalAmount = betTotalAmount;
    }

    public Integer getCurBetCount()
    {
        return curBetCount != null ? curBetCount.intValue() : 0;
    }

    public void setCurBetCount(Integer curBetCount)
    {
        this.curBetCount = curBetCount;
    }

    public String getRewardNumbers()
    {
        return rewardNumbers;
    }

    public void setRewardNumbers(String rewardNumbers)
    {
        this.rewardNumbers = rewardNumbers;
    }

    public Integer getState()
    {
        return state != null ? state : -99;
    }

    public void setState(Integer state)
    {
        this.state = state;
    }

    public String getBetTxnIDs()
    {
        return betTxnIDs;
    }

    public void setBetTxnIDs(String betTxnIDs)
    {
        this.betTxnIDs = betTxnIDs;
    }

    public Long getCurBlockHeight()
    {
        return curBlockHeight == null ? 0 : curBlockHeight;
    }

    public void setCurBlockHeight(Long curBlockHeight)
    {
        this.curBlockHeight = curBlockHeight;
    }

    public Long getPrevBlockHeight()
    {
        return prevBlockHeight == null ? 0 : prevBlockHeight;
    }

    public void setPrevBlockHeight(Long prevBlockHeight)
    {
        this.prevBlockHeight = prevBlockHeight;
    }

    public Long getLastUpadteBlockHeight()
    {
        return lastUpadteBlockHeight != null ? lastUpadteBlockHeight : 0;
    }

    public void setLastUpadteBlockHeight(Long lastUpadteBlockHeight)
    {
        this.lastUpadteBlockHeight = lastUpadteBlockHeight;
    }

    public String getUpdateFlag()
    {
        return updateFlag;
    }

    public void setUpdateFlag(String updateFlag)
    {
        this.updateFlag = updateFlag;
    }

    public Integer getPictureIndex()
    {
        return pictureIndex != null ? pictureIndex : 0;
    }

    public void setPictureIndex(Integer pictureIndex)
    {
        this.pictureIndex = pictureIndex;
    }

    public Integer getProgress()
    {
        return progress != null ? progress : 0;
    }

    public void setProgress(Integer progress)
    {
        this.progress = progress;
    }

    public String getPrizeTxID()
    {
        return prizeTxID != null ? prizeTxID : "";
    }

    public void setPrizeTxID(String prizeTxID)
    {
        this.prizeTxID = prizeTxID;
    }

    @Override
    public String toString()
    {
        return "OneLottery{" +
                "publisherName='" + publisherName + '\'' +
                ", lotteryId='" + lotteryId + '\'' +
                ", lotteryName='" + lotteryName + '\'' +
                '}';
    }
}
