package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRIZE_RULE".
 */
public class PrizeRule {

    private String ruleId;
    private String ruleName;
    private Integer percentage;
    private String updateFlag;
    private Boolean isHidden;

    public PrizeRule() {
    }

    public PrizeRule(String ruleId) {
        this.ruleId = ruleId;
    }

    public PrizeRule(String ruleId, String ruleName, Integer percentage, String updateFlag, Boolean isHidden) {
        this.ruleId = ruleId;
        this.ruleName = ruleName;
        this.percentage = percentage;
        this.updateFlag = updateFlag;
        this.isHidden = isHidden;
    }

    public String getRuleId() {
        return ruleId;
    }

    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public Integer getPercentage() {
        return percentage;
    }

    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    public String getUpdateFlag() {
        return updateFlag;
    }

    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    public Boolean getHidden() {
        return isHidden;
    }

    public void setHidden(Boolean isHidden) {
        this.isHidden = isHidden;
    }

}
