package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTION_DETAIL".
 */
public class TransactionDetail implements Cloneable {

    private String txId;
    private String myHash;
    private String myId;
    private String oppositeHash;
    private String oppositeUserId;
    private Long amount;
    private Long fee;
    private java.util.Date time;
    private String remark;
    private Integer type;

    public TransactionDetail() {
    }

    public TransactionDetail(String txId) {
        this.txId = txId;
    }

    public TransactionDetail(String txId, String myHash, String myId, String oppositeHash, String oppositeUserId, Long amount, Long fee, java.util.Date time, String remark, Integer type) {
        this.txId = txId;
        this.myHash = myHash;
        this.myId = myId;
        this.oppositeHash = oppositeHash;
        this.oppositeUserId = oppositeUserId;
        this.amount = amount;
        this.fee = fee;
        this.time = time;
        this.remark = remark;
        this.type = type;
    }

    public Object clone()
    {
        TransactionDetail o = null;
        try
        {
            o = (TransactionDetail) super.clone();
        }
        catch (CloneNotSupportedException e)
        {
        }
        return o;
    }

    public String getTxId() {
        return txId;
    }

    public void setTxId(String txId) {
        this.txId = txId;
    }

    public String getMyHash() {
        return myHash;
    }

    public void setMyHash(String myHash) {
        this.myHash = myHash;
    }

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    public String getOppositeHash() {
        return oppositeHash;
    }

    public void setOppositeHash(String oppositeHash) {
        this.oppositeHash = oppositeHash;
    }

    public String getOppositeUserId() {
        return oppositeUserId;
    }

    public void setOppositeUserId(String oppositeUserId) {
        this.oppositeUserId = oppositeUserId;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getFee() {
        return fee;
    }

    public void setFee(Long fee) {
        this.fee = fee;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
