package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_INFO".
 */
public class UserInfo implements Cloneable {

    private String userId;
    private String walletAddr;
    private Long balance;
    private Boolean isCurUser;
    private Long curBlockHeight;
    private Long prevBlockHeight;
    private String txnIDs;
    private Long lastGetBlockHeight;

    public UserInfo() {
    }

    public UserInfo(String userId) {
        this.userId = userId;
    }

    public UserInfo(String userId, String walletAddr, Long balance, Boolean isCurUser, Long curBlockHeight, Long prevBlockHeight, String txnIDs, Long lastGetBlockHeight) {
        this.userId = userId;
        this.walletAddr = walletAddr;
        this.balance = balance;
        this.isCurUser = isCurUser;
        this.curBlockHeight = curBlockHeight;
        this.prevBlockHeight = prevBlockHeight;
        this.txnIDs = txnIDs;
        this.lastGetBlockHeight = lastGetBlockHeight;
    }

    @Override
    public Object clone() throws CloneNotSupportedException
    {
        UserInfo u = null;
        try
        {
            u = (UserInfo) super.clone();
        }
        catch (CloneNotSupportedException e)
        {
            e.printStackTrace();
        }
        return u;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getWalletAddr() {
        return walletAddr;
    }

    public void setWalletAddr(String walletAddr) {
        this.walletAddr = walletAddr;
    }

    public Long getBalance() {
        return balance;
    }

    public void setBalance(Long balance) {
        this.balance = balance;
    }

    public Boolean getIsCurUser() {
        return isCurUser;
    }

    public void setIsCurUser(Boolean isCurUser) {
        this.isCurUser = isCurUser;
    }

    public Long getCurBlockHeight() {
        return curBlockHeight == null ? 0 : curBlockHeight;
    }

    public void setCurBlockHeight(Long curBlockHeight) {
        this.curBlockHeight = curBlockHeight;
    }

    public Long getPrevBlockHeight() {
        return prevBlockHeight == null ? 0 : prevBlockHeight;
    }

    public void setPrevBlockHeight(Long prevBlockHeight) {
        this.prevBlockHeight = prevBlockHeight;
    }

    public String getTxnIDs() {
        return txnIDs;
    }

    public void setTxnIDs(String txnIDs) {
        this.txnIDs = txnIDs;
    }

    public Long getLastGetBlockHeight() {
        return lastGetBlockHeight == null ? 0 : lastGetBlockHeight;
    }

    public void setLastGetBlockHeight(Long lastGetBlockHeight) {
        this.lastGetBlockHeight = lastGetBlockHeight;
    }

}
