package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "WITHDRAW_BANK_CARD".
 */
public class WithdrawBankCard implements Serializable{

    private String bankCardId;
    private String accountName;
    private String openingBank;
    private java.util.Date createTime;
    private Boolean isDefaultCard;
    private String userId;

    public WithdrawBankCard() {
    }

    public WithdrawBankCard(String bankCardId) {
        this.bankCardId = bankCardId;
    }

    public WithdrawBankCard(String bankCardId, String accountName, String openingBank, java.util.Date createTime, Boolean isDefaultCard, String userId) {
        this.bankCardId = bankCardId;
        this.accountName = accountName;
        this.openingBank = openingBank;
        this.createTime = createTime;
        this.isDefaultCard = isDefaultCard;
        this.userId = userId;
    }

    public String getBankCardId() {
        return bankCardId;
    }

    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getOpeningBank() {
        return openingBank;
    }

    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public Boolean getIsDefaultCard() {
        return isDefaultCard;
    }

    public void setIsDefaultCard(Boolean isDefaultCard) {
        this.isDefaultCard = isDefaultCard;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
