package com.peersafe.chainbet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "WITHDRAW_RECORD".
 */
public class WithdrawRecord implements Serializable{

    private String txId;
    private Integer state;
    private String openingBankName;
    private String accountName;
    private String accountId;
    private String userId;
    private String userHash;
    private Long amount;
    private String remitOrderNumber;
    private String remark;
    private java.util.Date createTime;
    private java.util.Date modifyTime;

    public WithdrawRecord() {}

    @Override
    public String toString()
    {
        return "WithdrawRecord{" +
                "txId='" + txId + '\'' +
                ", state=" + state +
                ", openingBankName='" + openingBankName + '\'' +
                ", accountName='" + accountName + '\'' +
                ", accountId='" + accountId + '\'' +
                ", userId='" + userId + '\'' +
                ", userHash='" + userHash + '\'' +
                ", amount=" + amount +
                ", remitOrderNumber='" + remitOrderNumber + '\'' +
                ", remark='" + remark + '\'' +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                '}';
    }

    public WithdrawRecord(String txId) {
        this.txId = txId;
    }

    public WithdrawRecord(String txId, Integer state, String openingBankName, String accountName, String accountId, String userId, String userHash, Long amount, String remitOrderNumber, String remark, java.util.Date createTime, java.util.Date modifyTime) {
        this.txId = txId;
        this.state = state;
        this.openingBankName = openingBankName;
        this.accountName = accountName;
        this.accountId = accountId;
        this.userId = userId;
        this.userHash = userHash;
        this.amount = amount;
        this.remitOrderNumber = remitOrderNumber;
        this.remark = remark;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
    }

    public String getTxId() {
        return txId;
    }

    public void setTxId(String txId) {
        this.txId = txId;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getOpeningBankName() {
        return openingBankName;
    }

    public void setOpeningBankName(String openingBankName) {
        this.openingBankName = openingBankName;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserHash() {
        return userHash;
    }

    public void setUserHash(String userHash) {
        this.userHash = userHash;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getRemitOrderNumber() {
        return remitOrderNumber;
    }

    public void setRemitOrderNumber(String remitOrderNumber) {
        this.remitOrderNumber = remitOrderNumber;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public java.util.Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(java.util.Date modifyTime) {
        this.modifyTime = modifyTime;
    }

}
